UPDATE BASE FILE

diff --git a/.github/workflows/03_ui_tests_ALL.yml b/.github/workflows/03_ui_tests_ALL.yml
--- a/.github/workflows/03_ui_tests_ALL.yml
+++ b/.github/workflows/03_ui_tests_ALL.yml
@@ -33,7 +33,7 @@ jobs:
             echo "package-lock.json not found, running npm install to generate it..."
             npm install
           fi
-     # Step 4: Install dependencies
+      # Step 4: Install dependencies
       - name: Install dependencies
         run: npm ci
 
@@ -47,7 +47,7 @@ jobs:
 
       # Step 7: Upload test reports as artifacts (ensure the path exists)
       - name: Upload Reports
-        if: success() || failure()  # Ensure reports are uploaded even on failure
+        if: success() || failure() # Ensure reports are uploaded even on failure
         uses: actions/upload-artifact@v4
         with:
           name: UI Tests Report
